#!/usr/bin/env bash
# Displays information about subdomains.
display ()
{
    dom="$1"
    sub="$2"
    printf "The subdomain %s is a " "$sub"
    dig "$sub.$dom" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $4 }'
    printf " record and points to "
    dig "$sub.$dom" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $5 }'
    echo ""
}
if [ -z "$1" ];
then
    true
elif [ -z "$2" ];
then
    for subs in "www" "lb-01" "web-01" "web-02"
    do
	display "$1" "$subs"
    done
else
    display "$1" "$2"
fi 
