#!/usr/bin/env bash
# Installs nginx on a web server.
echo "Updating dependencies..."
sleep 2
sudo apt-get -y update
echo "Installing nginx..."
sleep 2
sudo apt-get -y install nginx
echo "Configuring nginx..."
sleep 2
Error="Ceci n'est pas une page"
echo "$Error" | sudo tee /usr/share/nginx/html/custom_404.html
echo "server {
    listen 80;
    listen [::]:80;
    error_page 404 /custom_404.html;
    
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=o_oenl2Be-w;
    }

    location /custom_404.html {
        root /usr/share/nginx/html;
    }
}" | sudo tee /etc/nginx/sites-available/default
echo "Starting nginx..."
sleep 2
sudo service nginx start
