#!/usr/bin/env bash
# Installs nginx on a web server.
echo "Updating dependencies..."
sleep 2
sudo apt-get -y update
echo "Installing nginx..."
sleep 2
sudo apt-get -y install nginx
echo "Configuring nginx..."
sleep 2
Error="Ceci n'est pas une page"
sudo touch 404.html
echo "$Error" > '404.html'
echo "server {
    listen 80;
    listen [::]:80;

    error_page 404 /404.html

    location = /404.html {
        internal;
        root 404.html;
    }
}" | sudo tee /etc/nginx/sites-available/default
echo "Starting nginx..."
sleep 2
sudo service nginx start
