#!/usr/bin/env bash
# Binds nginx to port 80
echo "Updating dependencies"
sudo apt-get -y update
sleep 2
echo "Reconfiguring nginx..."
cp -a /etc/nginx/nginx.conf{,.orig}
sudo sed -i 's/sites-enabled/sites-available/' /etc/nginx/nginx.conf
sleep 2
echo "Restarting nginx..."
sudo service nginx restart
sleep 2
