#!/usr/bin/env bash
#Displays count with other info on superstitius numbers
str1="bad luck from China"
str2="bad luck from Japan"
str3="bad luck from Italy"
count=1
while [ $count -le 20 ]
do
    case $count in
        4)
            echo "$count"
            echo "$str1"
            ;;
        9)
            echo "$count"
            echo "$str2"
            ;;
        17)
            echo "$count"
            echo "$str3"
            ;;
        *)
            echo "$count"
            ;;
    esac

    ((count++))
done
