#!/usr/bin/env bash
#Displays 12-hr clock
hour=0
str="Hour: "
while [ $hour -le 12 ]
do
    echo "${str}${hour}"
    min=1
    while [ $min -le 59 ]
    do
        echo "$min"
        ((min++))
    done
    ((hour++))
done
