#!/usr/bin/env bash
# Edits /etc/hosts with different configurations
cp /etc/hosts new_hosts
sudo sed -i 's/127.0.0.1/127.0.0.2/g' new_hosts
echo "8.8.8.8        facebook.com" | sudo tee -a new_hosts
cp -f new_hosts /etc/hosts
