#!/usr/bin/env bash
#Script to configure nginx to run with non-root user

#Change ownership of Nginx directories
sudo chown -R nginx:nginx /var/log/nginx /var/lib/nginx /etc/nginx/nginx.conf

#Modify nginx to run as new user
sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo chmod +r /etc/nginx/nginx.conf

#Restart nginx
sudo -u nginx service nginx restart
